name: E2E tests

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        uses: ./
        with:
          directory: "ci"
          test-runner-api-key: ${{ secrets.TEST_RUNNER_API_KEY }}
          test-runner-url: "https://api.testrunner.smartesting.com"
