name: E2E tests

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        uses: ./
        with:
          url: 'https://clark-smartesting.atlassian.net'
          steps-file: 'ci/e2e.json'
          test-runner-api-key: ${{ secrets.CI_ASTRIS_API_KEY }}
          test-runner-url: 'https://api.testrunner.smartesting.com'
